steps:
  - name: 'python:3.10'
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt
        python load_csv_to_bigquery.py

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 600s
